In [10]:
# _importing required libraries
import pandas as pd
import numpy as np
import os

In [2]:
input_file_path = os.getcwd() + f'/../data/processed_data.csv'
col_names = ['timestamp (s)', 'activityID', 'X1', 'Y1', 'Z1', 'X2', 'Y2', 'Z2']
main_df = pd.read_csv(input_file_path, header=None, names=col_names)
pd.Series(main_df['timestamp (s)']).is_unique
main_df

,timestamp (s),activityID,X1,Y1,Z1,X2,Y2,Z2
0,37.66,1,2.21530,8.27915,5.58753,-0.004750,0.037579,-0.011145
1,37.67,1,2.29196,7.67288,5.74467,-0.171710,0.025479,-0.009538
2,37.68,1,2.29090,7.14240,5.82342,-0.238241,0.011214,0.000831
3,37.69,1,2.21800,7.14365,5.89930,-0.192912,0.019053,0.013374
4,37.70,1,2.30106,7.25857,6.09259,-0.069961,-0.018328,0.004582
...,...,...,...,...,...,...,...,...
288214,974.50,3,-1.99794,3.94300,9.15686,-0.112651,-0.003501,-0.066523
288215,974.51,3,-2.00276,4.20689,8.96346,-0.179092,0.020300,-0.010637
288216,974.52,3,-1.96042,4.09413,9.11842,-0.285215,0.010714,-0.017346
288217,974.53,3,-1.97860,3.78659,8.65734,-0.347098,0.040476,-0.020536
288218,974.54,3,-2.13484,3.63499,8.54005,-0.369435,0.036868,0.014151

In [15]:
print(np_sequences[0][1])

[2.2153  2.29196 2.2909  2.218   2.30106 2.07165 2.41148 2.32815 2.25096
 2.14107]

In [16]:
print(np_sequences[0][1])

[2.07165 2.41148 2.32815 2.25096 2.14107 2.36727 2.43617 2.28661 2.21585
 2.24722]

In [17]:
print(np_sequences[0][2])

[2.36727 2.43617 2.28661 2.21585 2.24722 2.24615 2.13466 2.23039 2.24697
 2.14778]

In [7]:
window_length = 10
window_overlap = 5
sub_sequences = [[], [], [], [], [], []]
sequence_names = ['X1', 'Y1', 'Z1', 'X2', 'Y2', 'Z2']

In [8]:
window_index = 0
max_window_index = len(main_df.index)

while window_index <= (max_window_index - window_length):
    for idx in range(len(sub_sequences)):
        sub_sequences[idx].append(main_df[sequence_names[idx]][window_index:window_index+window_length])
    
    window_index += window_overlap

In [11]:
np_sequences = np.asarray(sub_sequences)
print(np_sequences)

[[[ 2.21530e+00  2.29196e+00  2.29090e+00 ...  2.32815e+00  2.25096e+00
    2.14107e+00]
  [ 2.07165e+00  2.41148e+00  2.32815e+00 ...  2.28661e+00  2.21585e+00
    2.24722e+00]
  [ 2.36727e+00  2.43617e+00  2.28661e+00 ...  2.23039e+00  2.24697e+00
    2.14778e+00]
  ...
  [-2.13404e+00 -2.20240e+00 -2.13324e+00 ... -2.16862e+00 -2.06862e+00
   -2.07183e+00]
  [-2.21443e+00 -2.13270e+00 -2.16862e+00 ... -1.83386e+00 -1.79260e+00
   -2.00730e+00]
  [-2.03003e+00 -1.75508e+00 -1.83386e+00 ... -2.04108e+00 -2.14776e+00
   -1.99794e+00]]

 [[ 8.27915e+00  7.67288e+00  7.14240e+00 ...  7.63431e+00  7.78598e+00
    7.52262e+00]
  [ 7.25965e+00  7.59780e+00  7.63431e+00 ...  7.67154e+00  7.59758e+00
    7.44419e+00]
  [ 7.63436e+00  7.63210e+00  7.67154e+00 ...  6.94763e+00  6.83817e+00
    6.76686e+00]
  ...
  [ 3.74881e+00  4.01631e+00  4.05199e+00 ...  3.63629e+00  3.63206e+00
    3.74487e+00]
  [ 3.63457e+00  3.55978e+00  3.63629e+00 ...  3.63232e+00  3.93588e+00
    3.94065e+00]
  [ 3.74558e+00  3.89765e+00  3.63232e+00 ...  3.75258e+00  3.94450e+00
    3.94300e+00]]

 [[ 5.58753e+00  5.74467e+00  5.82342e+00 ...  5.70686e+00  5.62821e+00
    5.78141e+00]
  [ 6.01218e+00  5.93915e+00  5.70686e+00 ...  5.59065e+00  5.74378e+00
    5.59082e+00]
  [ 5.74593e+00  5.55453e+00  5.59065e+00 ...  5.20737e+00  5.70833e+00
    6.13044e+00]
  ...
  [ 8.53968e+00  8.69170e+00  8.50018e+00 ...  8.65500e+00  8.27164e+00
    8.15575e+00]
  [ 8.42340e+00  8.61731e+00  8.65500e+00 ...  8.50608e+00  8.54416e+00
    8.88732e+00]
  [ 8.27183e+00  8.54485e+00  8.50608e+00 ...  9.04139e+00  9.19310e+00
    9.15686e+00]]

 [[-4.75004e-03 -1.71710e-01 -2.38241e-01 ...  2.00328e-01  2.04098e-01
    1.71291e-01]
  [ 6.38951e-02  1.90837e-01  2.00328e-01 ... -5.80762e-02 -1.87787e-01
   -3.18051e-01]
  [ 9.97821e-02  4.58215e-03 -5.80762e-02 ... -5.46581e-01 -5.46750e-01
   -3.33107e-01]
  ...
  [ 1.21298e-01  6.39621e-02  3.51503e-02 ... -1.42307e-02  2.33860e-02
   -1.40249e-02]
  [-3.14645e-02 -2.25701e-02 -1.42307e-02 ...  2.27871e-02  2.17881e-02
   -2.83300e-02]
  [-1.45439e-02  3.59054e-03  2.27871e-02 ... -8.50592e-02 -7.72939e-02
   -1.12651e-01]]

 [[ 3.75788e-02  2.54788e-02  1.12136e-02 ... -9.26579e-03 -6.82564e-02
   -5.54110e-02]
  [ 7.17462e-03  3.11615e-03 -9.26579e-03 ... -1.51383e-02 -1.98241e-02
    9.63279e-03]
  [-3.85650e-02 -4.79050e-02 -1.51383e-02 ...  4.64301e-02  2.57062e-02
    7.25278e-02]
  ...
  [-9.59582e-02 -6.49537e-02 -8.05862e-02 ... -2.02588e-02 -1.49317e-02
    3.50823e-03]
  [-9.24841e-02 -6.22582e-02 -2.02588e-02 ...  8.98650e-03  2.29391e-02
    2.42020e-02]
  [ 8.50330e-04  3.68688e-02  8.98650e-03 ...  7.29374e-02  1.40164e-02
   -3.50146e-03]]

 [[-1.11450e-02 -9.53821e-03  8.30722e-04 ...  6.85673e-02  5.00003e-02
    2.15762e-02]
  [ 2.47007e-02  3.87616e-02  6.85673e-02 ... -8.52970e-03 -4.52587e-03
   -3.53578e-02]
  [ 1.11589e-02  3.63531e-02 -8.52970e-03 ... -1.00660e-01 -1.53974e-01
   -1.09563e-01]
  ...
  [-2.13300e-02 -4.28035e-02 -4.53556e-02 ... -6.99566e-02 -8.26629e-02
   -5.74883e-02]
  [-7.00064e-02 -4.13398e-02 -6.99566e-02 ... -3.42695e-02 -7.31052e-02
   -2.60900e-02]
  [-3.25129e-02 -1.18946e-02 -3.42695e-02 ... -1.18880e-02 -6.04822e-02
   -6.65231e-02]]]

In [14]:
print(np_sequences[0][0])

[2.2153  2.29196 2.2909  2.218   2.30106 2.07165 2.41148 2.32815 2.25096
 2.14107]