In [1]:
# _importing required libraries
import os
import collections

import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
from scipy import stats 
import statistics

import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
# _initializing constant variables
input_file_path = os.getcwd() + f'/../data/output_csv/processed_data.csv'
col_names = ['timestamp (s)', 'activityID', 'X1', 'Y1', 'Z1', 'X2', 'Y2', 'Z2']

In [3]:
# _loading preprocessed data to main dataframe
main_df = pd.read_csv(input_file_path,names=col_names)
main_df

,timestamp (s),activityID,X1,Y1,Z1,X2,Y2,Z2
0,37.66,1,2.21530,8.27915,5.58753,-0.004750,0.037579,-0.011145
1,37.67,1,2.29196,7.67288,5.74467,-0.171710,0.025479,-0.009538
2,37.68,1,2.29090,7.14240,5.82342,-0.238241,0.011214,0.000831
3,37.69,1,2.21800,7.14365,5.89930,-0.192912,0.019053,0.013374
4,37.70,1,2.30106,7.25857,6.09259,-0.069961,-0.018328,0.004582
...,...,...,...,...,...,...,...,...
1564137,3409.07,7,-1.68428,-8.97338,3.43203,-0.231392,-0.391747,0.180935
1564138,3409.08,7,-1.72527,-9.04964,3.35469,-0.252115,-0.338597,0.180709
1564139,3409.09,7,-1.53312,-8.97455,3.43429,-0.176675,-0.311570,0.172539
1564140,3409.10,7,-1.50362,-9.01479,3.20395,-0.173602,-0.291495,0.170721
1564141,3409.11,7,-1.61832,-9.20361,3.20287,-0.151012,-0.271370,0.188377

In [54]:
main_df = main_df[main_df['activityID'].isin([1])] 
main_df

,timestamp (s),activityID,X1,Y1,Z1,X2,Y2,Z2
0,37.66,1,2.21530,8.27915,5.58753,-0.004750,0.037579,-0.011145
1,37.67,1,2.29196,7.67288,5.74467,-0.171710,0.025479,-0.009538
2,37.68,1,2.29090,7.14240,5.82342,-0.238241,0.011214,0.000831
3,37.69,1,2.21800,7.14365,5.89930,-0.192912,0.019053,0.013374
4,37.70,1,2.30106,7.25857,6.09259,-0.069961,-0.018328,0.004582
...,...,...,...,...,...,...,...,...
1373608,308.96,1,-9.48966,-1.60911,1.21195,0.017997,-0.018442,-0.025190
1373609,308.97,1,-9.63654,-1.75836,1.36420,0.036515,0.030253,-0.030061
1373610,308.98,1,-9.44652,-1.60806,1.36654,0.026773,-0.012287,-0.049945
1373611,308.99,1,-9.55481,-1.64379,1.51899,0.032658,-0.001391,-0.022777
1373612,309.00,1,-9.55267,-1.52963,1.55712,-0.006588,0.025244,-0.032457

# Generating subsequences for each sequence of the data

In [53]:
window_length = 30
window_overlap = 10
max_window_index = len(main_df)
a1=main_df[['X1', 'Y1','Z1']]
window_index = 0
Features=[]
while window_index <= (max_window_index - window_length):
    a=a1.iloc[window_index:window_index+window_length]
    c=a1.values.tolist()
    print((window_index+window_length)-1)
    features=[(c[(window_index+window_length)-1][1]-c[window_index][1])-(c[(window_index+window_length)-1][0]-c[window_index][0]),(c[(window_index+window_length)-1][2]-c[window_index][2])-(c[(window_index+window_length)-1][0]-c[window_index][0])]
    Features.append(features)
    window_index += window_overlap

29
39
49
59
69
79
89
99
109
119
129
139
149
159
169
179
189
199
209
219
229
239
249
259
269
279
289
299
309
319
329
339
349
359
369
379
389
399
409
419
429
439
449
459
469
479
489
499
509
519
529
539
549
559
569
579
589
599
609
619
629
639
649
659
669
679
689
699
709
719
729
739
749
759
769
779
789
799
809
819
829
839
849
859
869
879
889
899
909
919
929
939
949
959
969
979
989
999
1009
1019
1029
1039
1049
1059
1069
1079
1089
1099
1109
1119
1129
1139
1149
1159
1169
1179
1189
1199
1209
1219
1229
1239
1249
1259
1269
1279
1289
1299
1309
1319
1329
1339
1349
1359
1369
1379
1389
1399
1409
1419
1429
1439
1449
1459
1469
1479
1489
1499
1509
1519
1529
1539
1549
1559
1569
1579
1589
1599
1609
1619
1629
1639
1649
1659
1669
1679
1689
1699
1709
1719
1729
1739
1749
1759
1769
1779
1789
1799
1809
1819
1829
1839
1849
1859
1869

KeyboardInterrupt:

In [46]:
Features

[[-0.6822999999999997, 0.26811000000000007],
 [0.008969999999999256, -0.59693],
 [-0.6480100000000006, 0.6039999999999996]]

In [47]:
main_df.head(20)

,timestamp (s),activityID,X1,Y1,Z1,X2,Y2,Z2
0,37.66,1,2.21530,8.27915,5.58753,-0.004750,0.037579,-0.011145
1,37.67,1,2.29196,7.67288,5.74467,-0.171710,0.025479,-0.009538
2,37.68,1,2.29090,7.14240,5.82342,-0.238241,0.011214,0.000831
3,37.69,1,2.21800,7.14365,5.89930,-0.192912,0.019053,0.013374
4,37.70,1,2.30106,7.25857,6.09259,-0.069961,-0.018328,0.004582
5,37.71,1,2.07165,7.25965,6.01218,0.063895,0.007175,0.024701
6,37.72,1,2.41148,7.59780,5.93915,0.190837,0.003116,0.038762
7,37.73,1,2.32815,7.63431,5.70686,0.200328,-0.009266,0.068567
8,37.74,1,2.25096,7.78598,5.62821,0.204098,-0.068256,0.050000
9,37.75,1,2.14107,7.52262,5.78141,0.171291,-0.055411,0.021576
10,37.76,1,2.36727,7.63436,5.74593,0.099782,-0.038565,0.011159
11,37.77,1,2.43617,7.63210,5.55453,0.004582,-0.047905,0.036353
12,37.78,1,2.28661,7.67154,5.59065,-0.058076,-0.015138,-0.008530
13,37.79,1,2.21585,7.59758,5.74378,-0.187787,-0.019824,-0.004526
14,37.80,1,2.24722,7.44419,5.59082,-0.318051,0.009633,-0.035358
15,37.81,1,2.24615,7.48180,5.55219,-0.431227,0.002685,-0.062964
16,37.82,1,2.13466,7.18017,5.66700,-0.501808,0.002804,-0.103990
17,37.83,1,2.23039,6.94763,5.20737,-0.546581,0.046430,-0.100660
18,37.84,1,2.24697,6.83817,5.70833,-0.546750,0.025706,-0.153974
19,37.85,1,2.14778,6.76686,6.13044,-0.333107,0.072528,-0.109563

In [22]:
window_index = 0

while window_index <= (max_window_index - window_length):
    a=main_df.iloc[0:10]
    b=a[['X1', 'Y1','Z1']]
    c=b.values.tolist()

    activity_sequence = main_df[sequence_names[0]][window_index:window_index+window_length].tolist()

    if len(set(activity_sequence)) == 1:
        sub_sequences[0].append(activity_sequence[0])
        
        for idx in range(1, num_of_subsequences):
            sub_sequences[idx].append(main_df[sequence_names[idx]][window_index:window_index+window_length].tolist())

    window_index += window_overlap

# _converting into numpy arrays
np_sequences = np.asarray(sub_sequences[1:])
print(np_sequences.shape)

NameError: name 'sequence_names' is not defined

# Finding the statistics of the subsequences(mean,variance,skewness,IQR)

In [32]:
def subsequence_statistics(n):
    subsequences=np_sequences[n]
    Mean=[]
    Standard_deviation=[]
    Skewness=[]
    IQR=[]
    Min=[]
    Max=[]
    Median=[]
    Range=[]
    Lower_quartile=[]
    Middle_quartile=[]
    Upper_quartile=[]
    Coefficient_of_variation=[]
    Kurtosis=[]
    for i in range(0,len(subsequences)):
        
        mean=sum(subsequences[i])/len(subsequences[i])
        Mean.append(mean)
        
        std=statistics.stdev(subsequences[i])
        Standard_deviation.append(std)
        
        Cov=std/mean
        Coefficient_of_variation.append(Cov)
        
        minimum=min(subsequences[i])
        Min.append(minimum)
        
        maximum=max(subsequences[i])
        Max.append(maximum)
        
        range1=maximum-minimum
        Range.append(range1)
        
        skewness=stats.skew(subsequences[i])
        Skewness.append(skewness)
        
        median=statistics.median(subsequences[i])
        Median.append(median)
        
        q3,q2, q1 = np.percentile(subsequences[i], [75 ,50,25])
        
        Lower_quartile.append(q1)
        
        Middle_quartile.append(q2)
        
        Upper_quartile.append(q3)
        
        iqr = q3 - q1
        IQR.append(iqr)
        
        kurtosis=stats.kurtosis(subsequences[i])
        Kurtosis.append(kurtosis)
        
        
        
    return Mean,Variance,Skewness,IQR,Min,Max,Median,Range,Lower_quartile,Middle_quartile,Upper_quartile,Coefficient_of_variation,Kurtosis

In [33]:
Mean,Variance,Skewness,IQR,Min,Max,Median,Range,Lower_quartile,Middle_quartile,Upper_quartile,Coefficient_of_variation,Kurtosis=subsequence_statistics(0)
data = list(zip(Mean,Variance,Skewness,IQR,Min,Max,Median,Range,Lower_quartile,Middle_quartile,Upper_quartile,Coefficient_of_variation,Kurtosis))
X1_statistic_df=pd.DataFrame(data,columns=['Mean','Variance','Skewness','IQR','Min','Max','Median','Range','Lower_quartile','Middle_quartile','Upper_quartile','Coefficient_of_variation','Kurtosis'])

In [34]:
X1_statistic_df

,Mean,Variance,Skewness,IQR,Min,Max,Median,Range,Lower_quartile,Middle_quartile,Upper_quartile,Coefficient_of_variation,Kurtosis
0,2.252053,0.008409,-0.336519,0.082810,2.07165,2.41148,2.270930,0.33983,2.215975,2.270930,2.298785,0.042920,-0.306746
1,2.275643,0.012021,-0.274613,0.133798,2.07165,2.43617,2.268785,0.36452,2.223693,2.268785,2.357490,0.050786,-0.815917
2,2.255907,0.007474,0.640422,0.057278,2.13466,2.43617,2.246560,0.30151,2.219485,2.246560,2.276763,0.040395,-0.195660
3,2.209783,0.006058,0.898379,0.096855,2.11880,2.38759,2.197090,0.26879,2.149910,2.197090,2.246765,0.037127,0.108338
4,2.214889,0.008036,0.179849,0.106895,2.06309,2.38759,2.214925,0.32450,2.158173,2.214925,2.265068,0.042663,-0.539171
...,...,...,...,...,...,...,...,...,...,...,...,...,...
312709,-1.183654,0.036115,-0.337586,0.277469,-1.52620,-0.92127,-1.175740,0.60493,-1.302588,-1.175740,-1.025119,-0.169239,-0.970320
312710,-1.225540,0.024752,0.742694,0.211905,-1.40156,-0.92127,-1.281200,0.48029,-1.342832,-1.281200,-1.130928,-0.135318,-0.815087
312711,-1.427101,0.017851,-0.946551,0.152780,-1.72474,-1.26271,-1.391360,0.46203,-1.498155,-1.391360,-1.345375,-0.098685,-0.033033
312712,-1.569999,0.012696,0.620479,0.112880,-1.72474,-1.34578,-1.570640,0.37896,-1.648625,-1.570640,-1.535745,-0.075650,-0.531426
312713,-1.639572,0.003601,0.472361,0.096680,-1.72527,-1.53312,-1.648090,0.19215,-1.686485,-1.648090,-1.589805,-0.038581,-1.051898

In [37]:
Mean1,Variance1,Skewness1,IQR1,Min1,Max1,Median1,Range1,Lower_quartile1,Middle_quartile1,Upper_quartile1,Coefficient_of_variation1,Kurtosis1=subsequence_statistics(1)
data1 = list(zip(Mean1,Variance1,Skewness1,IQR1,Min1,Max1,Median1,Range1,Lower_quartile1,Middle_quartile1,Upper_quartile1,Coefficient_of_variation1,Kurtosis1))
Y1_statistic_df=pd.DataFrame(data1,columns=['Mean','Variance','Skewness','IQR','Min','Max','Median','Range','Lower_quartile','Middle_quartile','Upper_quartile','Coefficient_of_variation','Kurtosis'])

In [38]:
Y1_statistic_df

,Mean,Variance,Skewness,IQR,Min,Max,Median,Range,Lower_quartile,Middle_quartile,Upper_quartile,Coefficient_of_variation,Kurtosis
0,7.529701,0.008409,0.776929,0.404397,7.14240,8.27915,7.560210,1.13675,7.258840,7.560210,7.663238,0.046619,0.055694
1,7.578013,0.012021,-0.978257,0.092988,7.25965,7.78598,7.614950,0.52633,7.541360,7.614950,7.634348,0.018887,0.700412
2,7.319440,0.007474,-0.526098,0.617705,6.76686,7.67154,7.462995,0.90468,7.005765,7.462995,7.623470,0.048513,-1.384370
3,7.492952,0.006058,0.267195,0.974205,6.76686,8.35964,7.371750,1.59278,7.005765,7.371750,7.979970,0.079187,-1.379431
4,7.554829,0.008036,0.416954,0.834438,6.87808,8.35964,7.371900,1.48156,7.145533,7.371900,7.979970,0.069569,-1.268360
...,...,...,...,...,...,...,...,...,...,...,...,...,...
312709,-9.628063,0.036115,-0.969804,0.898965,-11.34900,-8.71230,-9.220640,2.63670,-9.994045,-9.220640,-9.095080,-0.094573,-0.524196
312710,-8.944289,0.024752,-0.265386,0.297143,-9.27684,-8.71001,-8.919045,0.56683,-9.074397,-8.919045,-8.777255,-0.022048,-1.161983
312711,-8.864508,0.017851,0.356315,0.206175,-9.04661,-8.63556,-8.880140,0.41105,-8.973538,-8.880140,-8.767362,-0.015112,-1.073197
312712,-8.864200,0.012696,0.856001,0.131757,-8.97434,-8.63556,-8.878445,0.33878,-8.954248,-8.878445,-8.822490,-0.011904,0.198572
312713,-8.932233,0.003601,0.454440,0.105180,-9.04964,-8.78490,-8.973525,0.26474,-8.974498,-8.973525,-8.869317,-0.009675,-1.041499

In [39]:
Mean2,Variance2,Skewness2,IQR2,Min2,Max2,Median2,Range2,Lower_quartile2,Middle_quartile2,Upper_quartile2,Coefficient_of_variation2,Kurtosis2=subsequence_statistics(2)
data2 = list(zip(Mean2,Variance2,Skewness2,IQR2,Min2,Max2,Median2,Range2,Lower_quartile2,Middle_quartile2,Upper_quartile2,Coefficient_of_variation2,Kurtosis2))
Z1_statistic_df=pd.DataFrame(data2,columns=['Mean','Variance','Skewness','IQR','Min','Max','Median','Range','Lower_quartile','Middle_quartile','Upper_quartile','Coefficient_of_variation','Kurtosis'])

In [40]:
Z1_statistic_df

,Mean,Variance,Skewness,IQR,Min,Max,Median,Range,Lower_quartile,Middle_quartile,Upper_quartile,Coefficient_of_variation,Kurtosis
0,5.821532,0.008409,0.182114,0.212875,5.58753,6.09259,5.802415,0.50506,5.716312,5.802415,5.929188,0.028197,-1.035491
1,5.729352,0.012021,0.681666,0.172373,5.55453,6.01218,5.725320,0.45765,5.600167,5.725320,5.772540,0.026466,-0.636364
2,5.649104,0.007474,0.243501,0.171357,5.20737,6.13044,5.628910,0.92307,5.563560,5.628910,5.734917,0.040630,1.098092
3,5.917241,0.006058,-0.689642,0.539140,5.20737,6.28229,6.050065,1.07492,5.677333,6.050065,6.216473,0.061612,-0.716511
4,6.051815,0.008036,-0.340160,0.269952,5.74226,6.28229,6.071780,0.54003,5.937183,6.071780,6.207135,0.031939,-1.074008
...,...,...,...,...,...,...,...,...,...,...,...,...,...
312709,4.061379,0.036115,0.958346,0.789608,3.59588,5.21283,3.768510,1.61695,3.634532,3.768510,4.424140,0.135988,-0.295702
312710,3.692814,0.024752,0.881739,0.213673,3.35937,4.24783,3.613375,0.88846,3.563652,3.613375,3.777325,0.071013,0.096779
312711,3.527879,0.017851,1.119624,0.239597,3.32049,3.97533,3.494550,0.65484,3.377898,3.494550,3.617495,0.055393,0.725999
312712,3.437216,0.012696,0.545761,0.195778,3.27750,3.62682,3.394155,0.34932,3.354732,3.394155,3.550510,0.037704,-1.233902
312713,3.405614,0.003601,1.270478,0.077200,3.27750,3.62601,3.394155,0.34851,3.355250,3.394155,3.432450,0.026830,1.693366

In [41]:
Mean3,Variance3,Skewness3,IQR3,Min3,Max3,Median3,Range3,Lower_quartile3,Middle_quartile3,Upper_quartile3,Coefficient_of_variation3,Kurtosis3=subsequence_statistics(3)
data3 = list(zip(Mean3,Variance3,Skewness3,IQR3,Min3,Max3,Median3,Range3,Lower_quartile3,Middle_quartile3,Upper_quartile3,Coefficient_of_variation3,Kurtosis3))
X2_statistic_df=pd.DataFrame(data3,columns=['Mean','Variance','Skewness','IQR','Min','Max','Median','Range','Lower_quartile','Middle_quartile','Upper_quartile','Coefficient_of_variation','Kurtosis'])

In [42]:
X2_statistic_df

,Mean,Variance,Skewness,IQR,Min,Max,Median,Range,Lower_quartile,Middle_quartile,Upper_quartile,Coefficient_of_variation,Kurtosis
0,0.015287,0.008409,-0.218268,0.332223,-0.238241,0.204098,0.029573,0.442339,-0.146273,0.029573,0.185950,11.489622,-1.537332
1,0.037090,0.012021,-0.855509,0.228362,-0.318051,0.204098,0.081839,0.522149,-0.042412,0.081839,0.185950,4.820034,-0.469741
2,-0.281902,0.007474,0.355277,0.393659,-0.546750,0.099782,-0.325579,0.646532,-0.484163,-0.325579,-0.090504,-0.837363,-1.281498
3,-0.149742,0.006058,0.108288,0.672093,-0.546750,0.293617,-0.205086,0.840367,-0.484163,-0.205086,0.187930,-2.396614,-1.740372
4,0.173707,0.008036,-0.795303,0.150691,-0.077064,0.309597,0.184169,0.386661,0.118000,0.184169,0.268690,0.682577,-0.033440
...,...,...,...,...,...,...,...,...,...,...,...,...,...
312709,-0.380837,0.036115,-1.352225,0.306852,-1.208770,-0.092998,-0.197744,1.115772,-0.459521,-0.197744,-0.152669,-0.988209,0.371143
312710,-0.159550,0.024752,-0.131516,0.051219,-0.229152,-0.092998,-0.153336,0.136154,-0.188509,-0.153336,-0.137290,-0.253890,-0.687669
312711,-0.206995,0.017851,0.113644,0.078327,-0.282811,-0.119932,-0.219875,0.162879,-0.238100,-0.219875,-0.159774,-0.268807,-1.238068
312712,-0.241736,0.012696,0.084069,0.034245,-0.282811,-0.194346,-0.238633,0.088465,-0.259957,-0.238633,-0.225712,-0.117319,-0.923957
312713,-0.235318,0.003601,0.906162,0.030617,-0.266218,-0.176675,-0.244966,0.089543,-0.255665,-0.244966,-0.225048,-0.126663,-0.430154

In [43]:
Mean4,Variance4,Skewness4,IQR4,Min4,Max4,Median4,Range4,Lower_quartile4,Middle_quartile4,Upper_quartile4,Coefficient_of_variation4,Kurtosis4=subsequence_statistics(4)
data4 = list(zip(Mean4,Variance4,Skewness4,IQR4,Min4,Max4,Median4,Range4,Lower_quartile4,Middle_quartile4,Upper_quartile4,Coefficient_of_variation4,Kurtosis4))
Y2_statistic_df=pd.DataFrame(data1,columns=['Mean','Variance','Skewness','IQR','Min','Max','Median','Range','Lower_quartile','Middle_quartile','Upper_quartile','Coefficient_of_variation','Kurtosis'])

In [44]:
Y2_statistic_df

,Mean,Variance,Skewness,IQR,Min,Max,Median,Range,Lower_quartile,Middle_quartile,Upper_quartile,Coefficient_of_variation,Kurtosis
0,7.529701,0.008409,0.776929,0.404397,7.14240,8.27915,7.560210,1.13675,7.258840,7.560210,7.663238,0.046619,0.055694
1,7.578013,0.012021,-0.978257,0.092988,7.25965,7.78598,7.614950,0.52633,7.541360,7.614950,7.634348,0.018887,0.700412
2,7.319440,0.007474,-0.526098,0.617705,6.76686,7.67154,7.462995,0.90468,7.005765,7.462995,7.623470,0.048513,-1.384370
3,7.492952,0.006058,0.267195,0.974205,6.76686,8.35964,7.371750,1.59278,7.005765,7.371750,7.979970,0.079187,-1.379431
4,7.554829,0.008036,0.416954,0.834438,6.87808,8.35964,7.371900,1.48156,7.145533,7.371900,7.979970,0.069569,-1.268360
...,...,...,...,...,...,...,...,...,...,...,...,...,...
312709,-9.628063,0.036115,-0.969804,0.898965,-11.34900,-8.71230,-9.220640,2.63670,-9.994045,-9.220640,-9.095080,-0.094573,-0.524196
312710,-8.944289,0.024752,-0.265386,0.297143,-9.27684,-8.71001,-8.919045,0.56683,-9.074397,-8.919045,-8.777255,-0.022048,-1.161983
312711,-8.864508,0.017851,0.356315,0.206175,-9.04661,-8.63556,-8.880140,0.41105,-8.973538,-8.880140,-8.767362,-0.015112,-1.073197
312712,-8.864200,0.012696,0.856001,0.131757,-8.97434,-8.63556,-8.878445,0.33878,-8.954248,-8.878445,-8.822490,-0.011904,0.198572
312713,-8.932233,0.003601,0.454440,0.105180,-9.04964,-8.78490,-8.973525,0.26474,-8.974498,-8.973525,-8.869317,-0.009675,-1.041499

In [46]:
Mean5,Variance5,Skewness5,IQR5,Min5,Max5,Median5,Range5,Lower_quartile5,Middle_quartile5,Upper_quartile5,Coefficient_of_variation5,Kurtosis5=subsequence_statistics(5)
data5 = list(zip(Mean5,Variance5,Skewness5,IQR5,Min5,Max5,Median5,Range5,Lower_quartile5,Middle_quartile5,Upper_quartile5,Coefficient_of_variation5,Kurtosis5))
Z2_statistic_df=pd.DataFrame(data5,columns=['Mean','Variance','Skewness','IQR','Min','Max','Median','Range','Lower_quartile','Middle_quartile','Upper_quartile','Coefficient_of_variation','Kurtosis'])

In [47]:
Z2_statistic_df

,Mean,Variance,Skewness,IQR,Min,Max,Median,Range,Lower_quartile,Middle_quartile,Upper_quartile,Coefficient_of_variation,Kurtosis
0,0.020171,0.008409,0.515314,0.033478,-0.011145,0.068567,0.017475,0.079712,0.001768,0.017475,0.035246,1.293497,-0.778305
1,0.020270,0.012021,-0.254100,0.038764,-0.035358,0.068567,0.023138,0.103925,-0.000605,0.023138,0.038159,1.512533,-0.617141
2,-0.053205,0.007474,-0.118203,0.097631,-0.153974,0.036353,-0.049161,0.190327,-0.103157,-0.049161,-0.005527,-1.173830,-1.246186
3,-0.070908,0.006058,-0.402838,0.069828,-0.153974,-0.016716,-0.061250,0.137258,-0.103157,-0.061250,-0.033329,-0.635257,-0.878765
4,-0.016435,0.008036,-0.533773,0.029877,-0.059536,0.011946,-0.017332,0.071482,-0.024957,-0.017332,0.004920,-1.548928,-0.910721
...,...,...,...,...,...,...,...,...,...,...,...,...,...
312709,0.201365,0.036115,-0.078329,0.044562,0.167114,0.231698,0.196794,0.064584,0.181244,0.196794,0.225805,0.124598,-1.511472
312710,0.215641,0.024752,0.133537,0.026773,0.195168,0.245158,0.220689,0.049990,0.198910,0.220689,0.225683,0.079255,-1.147366
312711,0.219138,0.017851,-0.104639,0.013745,0.191044,0.245158,0.219018,0.054114,0.211884,0.219018,0.225628,0.072470,-0.482340
312712,0.206887,0.012696,0.397021,0.018759,0.182927,0.237664,0.206103,0.054737,0.197439,0.206103,0.216198,0.076791,-0.385701
312713,0.185800,0.003601,0.156841,0.024460,0.165786,0.210514,0.181931,0.044728,0.174582,0.181931,0.199042,0.084295,-1.284332